-- V10__health_score.sql — daily Portfolio Health Score for trend (Story 3.8/3.9, FR-6/FR-7).
--
-- One score per day (scored_on UNIQUE → idempotent upsert) with the explained breakdown stored as
-- JSON. The score itself is computed live on demand; this table feeds the 30-day trend. Forward-only.

CREATE TABLE health_score (
    id          bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scored_on   date          NOT NULL UNIQUE,
    score       integer       NOT NULL,
    breakdown   jsonb         NOT NULL,   -- serialized List<HealthDeduction>
    created_at  timestamptz   NOT NULL DEFAULT now()
);
