-- V11__news_articles.sql — ingested news for Agent 1 (Story 4.1, FR-8).
--
-- One row per ingested article, deduplicated on (source, external_id) so a re-run of an
-- overlapping ingestion window is idempotent. `tickers` holds the relevance tags (which held
-- symbols the article mentions); sentiment is added later (Story 4.2) and left null until then.
-- Forward-only.

CREATE TABLE news_articles (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source        text         NOT NULL,
    external_id   text         NOT NULL,
    url           text,
    headline      text         NOT NULL,
    summary       text,
    published_at  timestamptz  NOT NULL,
    tickers       text[]       NOT NULL DEFAULT '{}',
    ingested_at   timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (source, external_id)
);

-- The feed and downstream tagging query newest-first.
CREATE INDEX idx_news_articles_published_at ON news_articles (published_at DESC);
