-- V13__source_credibility.sql — Source Credibility Engine for Agent 1 (Story 4.3, FR-9).
--
-- One row per news source, scored 0–100. Unknown sources are created at 35 (Bronze). Scores move
-- +2 on a correct signal outcome, −3 on incorrect (clamped 0–100); a source below 10 is auto-blocked.
-- `tier` is the derived band (Platinum/Gold/Silver/Bronze/Flagged/Blocked), stored for query/display.
-- correct/incorrect counts are kept for transparency. Forward-only.

CREATE TABLE source_credibility (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source          text         NOT NULL UNIQUE,
    score           integer      NOT NULL,
    tier            text         NOT NULL,
    blocked         boolean      NOT NULL DEFAULT false,
    correct_count   integer      NOT NULL DEFAULT 0,
    incorrect_count integer      NOT NULL DEFAULT 0,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now()
);
