-- V14__stranger_alerts.sql — Stranger Danger Protocol output for Agent 1 (Story 4.4, FR-10).
--
-- One row per "stranger" ticker (not held / not watch-listed) currently under heavy news coverage.
-- Unique on ticker so each cycle upserts the latest assessment. risk_score is the 0–100
-- pump-and-dump score; required_consensus is the elevated agent-agreement bar (6 of 7) Agent 5 must
-- clear before recommending this ticker. avg_source_score traces the covering sources' credibility.
-- Forward-only.

CREATE TABLE stranger_alerts (
    id                 bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker             text          NOT NULL UNIQUE,
    coverage_count     integer       NOT NULL,
    distinct_sources   integer       NOT NULL,
    avg_source_score   numeric(5, 2),
    risk_score         integer       NOT NULL,
    required_consensus integer       NOT NULL,
    window_start       timestamptz   NOT NULL,
    detected_at        timestamptz   NOT NULL DEFAULT now(),
    updated_at         timestamptz   NOT NULL DEFAULT now()
);
