-- V15__calendar_events.sql — economic/earnings calendar for Agent 7 (Story 5.1, FR-21).
--
-- One row per upcoming event, deduplicated on (source, external_id) so Agent 7's daily run is
-- idempotent. `ticker` is null for macro events (Fed/CPI/jobs/GDP). `event_date` is the date the
-- event occurs (used for lead-time alerts in Story 5.2 and the pre-earnings quiet period in 5.3).
-- Forward-only.

CREATE TABLE calendar_events (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         text         NOT NULL,   -- EARNINGS | FED | CPI | JOBS | GDP | EX_DIVIDEND | LOCKUP
    ticker       text,                     -- null for macro events
    title        text         NOT NULL,
    event_date   date         NOT NULL,
    source       text         NOT NULL,
    external_id  text         NOT NULL,
    ingested_at  timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (source, external_id)
);

-- Lead-time scans (Story 5.2) and quiet-period lookups (Story 5.3) query by date / ticker.
CREATE INDEX idx_calendar_events_date ON calendar_events (event_date);
CREATE INDEX idx_calendar_events_ticker ON calendar_events (ticker);
