-- V16__calendar_event_alerts.sql — fired lead-time alerts for Agent 7 (Story 5.2, FR-22).
--
-- One row per (event, lead-day threshold) that has already been alerted, so the scanner never
-- re-queues the same reminder. urgency is GREEN (normal lead — goes in the briefing) or YELLOW
-- (within ~24h). Forward-only.

CREATE TABLE calendar_event_alerts (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   bigint       NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,
    lead_days  integer      NOT NULL,
    urgency    text         NOT NULL,
    fired_at   timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (event_id, lead_days)
);
