-- V17__recommendations.sql — Agent 5 recommendations + their signal diagnostic (Stories 6.1/6.2,
-- FR-11/FR-12). One recommendation per row with the auditable bull/bear probabilities and confidence
-- from the scoring engine; the child recommendation_signals rows are the per-agent diagnostic (each
-- agent's direction, weight, and rationale — conflicts included, never hidden). status drives the
-- Taken/Declined lifecycle (Story 6.7). Forward-only.

CREATE TABLE recommendations (
    id               bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker           text          NOT NULL,
    direction        text          NOT NULL,   -- BULLISH | BEARISH
    bull_probability numeric(5, 4) NOT NULL,
    bear_probability numeric(5, 4) NOT NULL,
    confidence       numeric(5, 4) NOT NULL,
    price_target     numeric(20, 4),
    horizon          text,
    status           text          NOT NULL DEFAULT 'PENDING',
    created_at       timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX idx_recommendations_ticker ON recommendations (ticker);
CREATE INDEX idx_recommendations_created ON recommendations (created_at DESC);

CREATE TABLE recommendation_signals (
    id                bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id bigint         NOT NULL REFERENCES recommendations(id) ON DELETE CASCADE,
    agent             text           NOT NULL,
    direction         text           NOT NULL,
    weight            numeric(10, 4) NOT NULL,
    signed_weight     numeric(10, 4) NOT NULL,
    rationale         text
);

CREATE INDEX idx_recommendation_signals_rec ON recommendation_signals (recommendation_id);
