-- V18__agent_graduation.sql — Agent 5 trust graduation (Story 6.6, FR-11). The single-row
-- agent_graduation holds the current state (SHADOW → PROBATION → ACTIVE → FROZEN); paper_trades is
-- the outcome history the state machine evaluates (overall win rate + rolling last-10). Forward-only.

CREATE TABLE agent_graduation (
    id         integer      PRIMARY KEY,    -- always 1 (singleton)
    state      text         NOT NULL,
    updated_at timestamptz  NOT NULL DEFAULT now()
);

INSERT INTO agent_graduation (id, state) VALUES (1, 'SHADOW');

CREATE TABLE paper_trades (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    won               boolean      NOT NULL,
    recommendation_id bigint,
    created_at        timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_paper_trades_created ON paper_trades (created_at DESC);
