-- V19__trade_decisions.sql — trade confirmation + rationale snapshot (Story 6.7, FR-14b). When the
-- user marks a recommendation Taken/Declined, an immutable JSON snapshot of the signals + their
-- free-text reasoning is stored. The actual outcome (WIN/LOSS) is tracked alongside it (without
-- mutating the snapshot) and feeds the graduation win-rate. Forward-only.

CREATE TABLE trade_decisions (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id bigint       NOT NULL REFERENCES recommendations(id),
    decision          text         NOT NULL,   -- TAKEN | DECLINED
    reasoning         text,
    snapshot          text         NOT NULL,   -- immutable JSON captured at decision time
    decided_at        timestamptz  NOT NULL DEFAULT now(),
    outcome           text,                     -- WIN | LOSS | null (pending)
    outcome_at        timestamptz
);

CREATE INDEX idx_trade_decisions_rec ON trade_decisions (recommendation_id);
