-- Agent 2 — Social Media Intelligence: crowd posts mentioning held tickers (StockTwits + Reddit),
-- each carrying a crowd sentiment. Dedup on (source, external_id).
CREATE TABLE social_posts (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker          text         NOT NULL,
    source          text         NOT NULL,
    external_id     text         NOT NULL,
    author          text,
    body            text,
    url             text,
    sentiment_label text,
    sentiment_score numeric,
    posted_at       timestamptz,
    ingested_at     timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (source, external_id)
);

CREATE INDEX idx_social_posts_ticker ON social_posts (ticker, posted_at DESC);
