-- Agent 4 — Financial Reports: SEC EDGAR insider activity (Form 4) for held tickers. One row per
-- filing, summarized to the dominant transaction. Dedup on accession number.
CREATE TABLE sec_filings (
    id               bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker           text         NOT NULL,
    cik              text         NOT NULL,
    accession        text         NOT NULL UNIQUE,
    form_type        text         NOT NULL,
    filed_at         date,
    url              text,
    insider_name     text,
    insider_title    text,
    transaction_type text,         -- BUY | SELL | GRANT | OTHER
    shares           numeric,
    value            numeric,
    ingested_at      timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_sec_filings_ticker ON sec_filings (ticker, filed_at DESC);
