-- Agent 6 — Cost Governor: a persisted record of every paid (cloud-model) call, so spend survives
-- restarts and can be summed month-to-date for budget governance (Epic 10).
CREATE TABLE cost_events (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at   timestamptz  NOT NULL DEFAULT now(),
    model         text         NOT NULL,
    source        text,
    input_tokens  bigint       NOT NULL DEFAULT 0,
    output_tokens bigint       NOT NULL DEFAULT 0,
    cost_usd      numeric      NOT NULL DEFAULT 0
);

CREATE INDEX idx_cost_events_occurred ON cost_events (occurred_at);
