-- Agent 3 — Internet Intelligence: broad web attention on held tickers from free public sources
-- (Hacker News discussion + Wikipedia pageviews). Dedup on (source, external_id).
CREATE TABLE web_mentions (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker          text         NOT NULL,
    source          text         NOT NULL,
    external_id     text         NOT NULL,
    title           text,
    url             text,
    score           bigint       NOT NULL DEFAULT 0,   -- HN points, or Wikipedia daily views
    sentiment_label text,                              -- HN only (keyword-classified); null for Wikipedia
    posted_at       timestamptz,
    ingested_at     timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (source, external_id)
);

CREATE INDEX idx_web_mentions_ticker ON web_mentions (ticker, posted_at DESC);
