-- F11 Personas: each MVP persona's cached verdict on a recommendation (one local-model call fills
-- all four). Cascade-deleted with the recommendation. Dedup on (recommendation_id, persona).
CREATE TABLE persona_verdicts (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id bigint       NOT NULL REFERENCES recommendations(id) ON DELETE CASCADE,
    persona           text         NOT NULL,
    stance            text         NOT NULL,   -- AGREE | DISAGREE | CAUTION
    rationale         text,
    created_at        timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (recommendation_id, persona)
);

CREATE INDEX idx_persona_verdicts_rec ON persona_verdicts (recommendation_id);
