-- Epic 8 (FR-17): one row per browser Web Push subscription. The endpoint is the push
-- service URL the backend POSTs encrypted payloads to; p256dh + auth are the subscription's
-- client keys (RFC 8291). Dedup on endpoint — re-subscribing the same device refreshes its keys.
CREATE TABLE push_subscriptions (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint    text         NOT NULL UNIQUE,
    p256dh      text         NOT NULL,
    auth        text         NOT NULL,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);
