-- Epic 8 (FR-16): the daily Morning Briefing — a local-model narrative over the portfolio,
-- overnight news, current recommendations and today's calendar. One row per generation; the
-- UI and the morning push read the most recent by generated_at.
CREATE TABLE briefings (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    headline     text         NOT NULL,
    body         text         NOT NULL,
    generated_at timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_briefings_generated_at ON briefings (generated_at DESC);
