-- Cash balances per account (FR-1 gap): the brokerage's "total value" includes uninvested cash that
-- the holdings import doesn't capture. One row per account+currency; folded into the CAD portfolio
-- total (and cost, so P&L is unaffected — cash is worth its face value).
CREATE TABLE cash_balances (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account     text         NOT NULL,
    currency    text         NOT NULL,           -- CAD | USD
    amount      numeric      NOT NULL DEFAULT 0,
    updated_at  timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (account, currency)
);
