-- Epic 6/9 (FR-11 follow-up): the Investor persona's paper-trading book. When Agent 5 (the Analyst)
-- makes a recommendation, the Investor opens a simulated fixed-notional position at the current price
-- and, after the recommendation's horizon, marks it to market. A closed trade "wins" on a positive
-- direction-adjusted return, and that outcome feeds the existing graduation/accuracy machinery — so
-- the track record is built autonomously instead of from manual input. On a loss, the Analyst's
-- post-mortem is stored in `review` so it can be surfaced and learned from.
CREATE TABLE simulated_trades (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id bigint,
    ticker            text         NOT NULL,
    direction         text         NOT NULL,            -- BULLISH | BEARISH
    notional          numeric(18,2) NOT NULL,           -- the pretend money committed (e.g. 100.00)
    entry_price       numeric(18,6) NOT NULL,
    shares            numeric(24,8) NOT NULL,
    entry_at          timestamptz  NOT NULL DEFAULT now(),
    horizon_days      int          NOT NULL,
    status            text         NOT NULL DEFAULT 'OPEN',  -- OPEN | CLOSED
    exit_price        numeric(18,6),
    return_pct        numeric(10,4),                    -- direction-adjusted realized return, %
    won               boolean,
    review            text,                             -- Analyst post-mortem (losses)
    closed_at         timestamptz
);

CREATE INDEX idx_simulated_trades_status ON simulated_trades (status);
CREATE INDEX idx_simulated_trades_entry_at ON simulated_trades (entry_at DESC);
