-- Curated "News to read" queue (Dashboard news section). Each row is one important, recent article
-- promoted from news_articles, with a local-model (Gemma) paragraph explaining what happened and its
-- likely market impact. The dashboard shows one card at a time; "Done Reading" deletes it and the next
-- highest-impact card surfaces. `summary` is NULL until the model has written the paragraph (a
-- background drip fills these), so the UI only ever shows ready cards. Cards are pruned once the
-- underlying article is older than the freshness window (news no later than ~1 day).
CREATE TABLE news_card (
    id            bigint            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id    bigint            NOT NULL UNIQUE REFERENCES news_articles (id) ON DELETE CASCADE,
    headline      text              NOT NULL,
    summary       text,                                  -- Gemma paragraph; NULL = pending generation
    source        text              NOT NULL,
    url           text,
    tickers       text[]            NOT NULL DEFAULT '{}',
    impact_score  double precision  NOT NULL DEFAULT 0,   -- relevance × (floor + |sentiment|), highest first
    published_at  timestamptz       NOT NULL,             -- when the news happened
    fetched_at    timestamptz       NOT NULL,             -- when Argus ingested it
    generated_at  timestamptz,                            -- when the summary was written
    created_at    timestamptz       NOT NULL DEFAULT now()
);

-- Next card to show: highest-impact card that already has a summary.
CREATE INDEX news_card_ready_idx ON news_card (impact_score DESC) WHERE summary IS NOT NULL;
-- Pruning stale cards by the underlying article's publish time.
CREATE INDEX news_card_published_idx ON news_card (published_at);
