-- Smart Cleanup agent (data-retention). Two supporting tables:
--
-- 1) sentiment_daily — the "roll up before you delete" store. Before the agent removes raw firehose
--    rows (social_posts / web_mentions / news_articles) it folds them into one row per
--    (kind, ticker, day): counts + sentiment/relevance SUMS (averages are sum/count on read). This
--    preserves the *pattern* (historical sentiment curves, volume baselines) at ~1% of the size, so
--    future events can still be linked to similar past setups after the raw rows are gone.
--
-- 2) cleanup_run — an audit/report of each agent run (dry-run or live): what it deleted, kept, rolled
--    up, and freed, plus a per-table JSON breakdown. Drives the "Last cleanup" panel in the Ops UI.

CREATE TABLE sentiment_daily (
    id             bigint            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind           text              NOT NULL,        -- SOCIAL | WEB | NEWS
    ticker         text              NOT NULL,
    day            date              NOT NULL,
    post_count     integer           NOT NULL DEFAULT 0,
    bullish_count  integer           NOT NULL DEFAULT 0,
    bearish_count  integer           NOT NULL DEFAULT 0,
    neutral_count  integer           NOT NULL DEFAULT 0,
    sentiment_sum  double precision  NOT NULL DEFAULT 0,  -- avg sentiment = sentiment_sum / post_count
    relevance_sum  double precision  NOT NULL DEFAULT 0,  -- avg relevance = relevance_sum / post_count
    first_at       timestamptz,
    last_at        timestamptz,
    updated_at     timestamptz       NOT NULL DEFAULT now(),
    UNIQUE (kind, ticker, day)
);

CREATE INDEX sentiment_daily_ticker_day_idx ON sentiment_daily (ticker, day);

CREATE TABLE cleanup_run (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at      timestamptz  NOT NULL DEFAULT now(),
    finished_at     timestamptz,
    dry_run         boolean      NOT NULL,
    deleted_rows    bigint       NOT NULL DEFAULT 0,
    kept_rows       bigint       NOT NULL DEFAULT 0,
    rolled_up_days  bigint       NOT NULL DEFAULT 0,
    freed_bytes     bigint       NOT NULL DEFAULT 0,
    report          jsonb        NOT NULL DEFAULT '{}'::jsonb,
    summary         text
);

CREATE INDEX cleanup_run_started_idx ON cleanup_run (started_at DESC);
