-- Analyst Logic Review (automated, LLM-proposes / backtest-decides). Each run: the local model reviews
-- the closed paper-trade record and proposes per-agent weight-multiplier factors; the agent then
-- backtests those factors by re-scoring every closed trade through the real scoring engine and adopts
-- them ONLY if they lower the Brier score (better-calibrated) without hurting accuracy, over a minimum
-- sample. So the LLM widens the search space; realized historical outcomes decide what actually ships.
-- This table is the audit log of every run (adopted or not), for the Ops UI.
CREATE TABLE logic_review (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ran_at          timestamptz  NOT NULL DEFAULT now(),
    model           text,                                 -- which model proposed (or 'n/a' when skipped)
    sample_size     int          NOT NULL DEFAULT 0,      -- closed trades the backtest ran over
    before_brier    double precision,                     -- current config's Brier on the backtest
    after_brier     double precision,                     -- proposed config's Brier
    before_accuracy double precision,
    after_accuracy  double precision,
    adopted         boolean      NOT NULL DEFAULT false,
    reason          text,                                 -- why adopted / rejected (human-readable)
    proposals       jsonb        NOT NULL DEFAULT '[]'::jsonb  -- [{agent,factor,why}] the LLM suggested
);

CREATE INDEX logic_review_ran_at_idx ON logic_review (ran_at DESC);
