-- Watchlist — the universe beyond your holdings that the agents also cover and Agent 5 recommends on.
-- Two feeders share this table: MANUAL (you add a ticker) and DISCOVERED (a future auto-discovery agent
-- promotes a trending market name, with an expiry). Composed with the portfolio by CompositeKnownUniverse
-- so widening it automatically widens news/social/SEC/calendar ingestion, Stranger Danger, and the
-- 6-hourly recommendation review — no per-agent wiring.
CREATE TABLE watchlist (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker      text         NOT NULL UNIQUE,
    source      text         NOT NULL DEFAULT 'MANUAL',   -- MANUAL | DISCOVERED
    note        text,                                     -- why it's here (free text or discovery reason)
    active      boolean      NOT NULL DEFAULT true,
    added_at    timestamptz  NOT NULL DEFAULT now(),
    expires_at  timestamptz                               -- for DISCOVERED entries; NULL = never expires
);

CREATE INDEX watchlist_active_idx ON watchlist (active) WHERE active;
