-- Breaking-news alerts — high-impact market-moving news that fires an immediate push notification.
-- The detector runs as each freshly-analyzed article lands (Agent 1's sentiment stage): a story alerts
-- if it's strongly material to your holdings (relevance × |sentiment| high) OR it hits a market-wide
-- breaking topic (war, Fed, tariffs, a Trump market remark, a crash, …). This table dedups repeat
-- headlines, rate-limits the feed, and gives an in-app record of what was pushed.
CREATE TABLE breaking_alert (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    headline        text         NOT NULL,
    url             text,
    tickers         text[]       NOT NULL DEFAULT '{}',
    reason          text         NOT NULL,          -- why it fired (impact vs which breaking topic)
    impact          double precision NOT NULL DEFAULT 0,
    sentiment_label text,
    created_at      timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX breaking_alert_created_idx ON breaking_alert (created_at DESC);
