-- Per-account metadata parsed from a brokerage statement's header (Portfolio-tab detail): who owns
-- the account (Joint vs Solo) and the holder name(s). The account number + type + currency are kept
-- in the existing `positions.account` / `cash_balances.account` label (which stays the import
-- reconcile key); this table adds only the owner identity, keyed by (institution, account) so both
-- positions and cash can look it up. Populated on import confirm; safe to be sparse.
CREATE TABLE account_meta (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution text,
    account     text         NOT NULL,
    owner_type  text,                            -- 'Joint' | 'Solo' (null when the parser couldn't tell)
    owner_name  text,                            -- e.g. 'Gaurav Oli & Varsha Gupta' or 'Gaurav Oli'
    updated_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT account_meta_unique UNIQUE (institution, account)
);

-- Staged parsed accounts for a pending import (mirrors raw_cash); applied to account_meta on confirm.
ALTER TABLE portfolio_imports ADD COLUMN raw_accounts text NOT NULL DEFAULT '[]';
