-- Deferred notifications (closes the Story 8.2 follow-up): NORMAL-tier alerts were "deferred to the
-- next briefing" and INFO-tier "to the weekly digest", but only the outcome was logged — the items
-- themselves vanished. Now they're persisted here; the morning briefing folds in pending BRIEFING
-- rows and a Sunday digest job summarizes pending DIGEST rows, each marking delivered_at.
CREATE TABLE deferred_notifications (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier         text         NOT NULL,
    title        text         NOT NULL,
    body         text,
    url          text,
    ticker       text,
    channel      text         NOT NULL CHECK (channel IN ('BRIEFING', 'DIGEST')),
    created_at   timestamptz  NOT NULL DEFAULT now(),
    delivered_at timestamptz
);

CREATE INDEX idx_deferred_notifications_pending
    ON deferred_notifications (channel, created_at) WHERE delivered_at IS NULL;
