-- Self-updating macro/geopolitical keyword list for Agent 8 (MacroRelevanceTagger). A fixed keyword
-- list can never be exhaustive, so MacroKeywordLearningService keeps it growing: every time the LLM
-- classification pass (SentimentAnalyzer's "macro" field) catches a story the keyword list missed,
-- that's logged as a miss; weekly, the model proposes new keywords from real misses, and a
-- deterministic gate (corroboration + a known-ambiguous-word stoplist — NOT the model's say-so)
-- decides what actually ships. Mirrors logic_review (V35)'s "LLM proposes, evidence decides, always
-- logged" shape.

-- The live keyword list, DB-backed so a learned keyword takes effect without a redeploy.
CREATE TABLE macro_keyword (
    keyword               text         PRIMARY KEY,
    added_at              timestamptz  NOT NULL DEFAULT now(),
    source                text         NOT NULL,             -- 'seed' | 'learned'
    why                   text,                               -- model's reasoning, null for seed rows
    corroborating_misses  int                                 -- distinct misses that supported it, null for seed rows
);

-- Seed from MacroRelevanceTagger.DEFAULT_KEYWORDS (the hand-curated list broadened to global coverage
-- earlier this session) so the live table starts exactly where the static list left off.
INSERT INTO macro_keyword (keyword, source) VALUES
    ('trump', 'seed'), ('tariff', 'seed'), ('tariffs', 'seed'), ('trade war', 'seed'),
    ('federal reserve', 'seed'), ('fomc', 'seed'), ('rate cut', 'seed'), ('rate hike', 'seed'),
    ('interest rate decision', 'seed'), ('white house', 'seed'), ('executive order', 'seed'),
    ('government shutdown', 'seed'), ('sanction', 'seed'), ('sanctions', 'seed'),
    ('yen', 'seed'), ('dollar', 'seed'), ('euro', 'seed'), ('yuan', 'seed'), ('renminbi', 'seed'),
    ('sterling', 'seed'), ('currency', 'seed'), ('forex', 'seed'), ('devaluation', 'seed'),
    ('currency intervention', 'seed'),
    ('bank of japan', 'seed'), ('boj', 'seed'), ('european central bank', 'seed'), ('ecb', 'seed'),
    ('people''s bank of china', 'seed'), ('pboc', 'seed'), ('bank of england', 'seed'), ('boe', 'seed'),
    ('reserve bank of india', 'seed'), ('rbi', 'seed'), ('swiss national bank', 'seed'), ('snb', 'seed'),
    ('bank of canada', 'seed'),
    ('nato', 'seed'), ('g7', 'seed'), ('g20', 'seed'), ('opec', 'seed'), ('united nations', 'seed'),
    ('security council', 'seed'), ('brexit', 'seed'), ('european union', 'seed'),
    ('invasion', 'seed'), ('ceasefire', 'seed'), ('coup', 'seed'), ('embargo', 'seed'),
    ('martial law', 'seed'), ('diplomatic crisis', 'seed');

-- Every LLM-only catch (SentimentAnalyzer said macro=true, the keyword list hadn't already tagged it)
-- — the raw evidence the weekly review learns from.
CREATE TABLE macro_keyword_miss (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id   bigint       NOT NULL REFERENCES news_articles (id),
    headline     text         NOT NULL,
    summary      text,
    detected_at  timestamptz  NOT NULL DEFAULT now(),
    reviewed     boolean      NOT NULL DEFAULT false
);

CREATE INDEX macro_keyword_miss_unreviewed_idx ON macro_keyword_miss (reviewed) WHERE NOT reviewed;

-- Audit log of every weekly review run (adopted or not) — the "learning feedback" record.
CREATE TABLE macro_keyword_review (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ran_at             timestamptz  NOT NULL DEFAULT now(),
    model              text,                                 -- which model proposed (or 'n/a' when skipped)
    misses_considered  int          NOT NULL DEFAULT 0,
    proposals          jsonb        NOT NULL DEFAULT '[]'::jsonb,  -- [{keyword,why,coveredMisses}] the model suggested
    adopted            jsonb        NOT NULL DEFAULT '[]'::jsonb,  -- subset of proposals that cleared the gate
    reason             text
);

CREATE INDEX macro_keyword_review_ran_at_idx ON macro_keyword_review (ran_at DESC);
