-- Cost Governor (Agent 6) tracks paid (Haiku) call counts via cost_events, but nothing anywhere
-- counts local-model (Gemma) calls — a separate, purpose-built table rather than reusing cost_events,
-- since that table is explicitly the "paid call" record (cost_usd is always meaningful there); a local
-- call has no cost, so folding it in would corrupt the existing paid-call count/spend queries.
create table local_model_calls (
    id           bigint       generated by default as identity primary key,
    occurred_at  timestamptz  not null default now(),
    tier         text         not null   -- SMALL | BIG
);

create index local_model_calls_occurred_at_idx on local_model_calls (occurred_at);
