-- Agent 9: on-demand, user-triggered stock research. A job plans itself (an ordered step list), works
-- through the plan gathering real per-ticker data from the same sources Agents 1/2/4/8 already collect,
-- can revise its own remaining steps mid-run, then synthesizes a long-form report. Persisted (not the
-- volatile in-memory shape BackupTriggerService uses) since progress must survive a page refresh and
-- multiple tickers can be researched concurrently, keyed by job id rather than a single global slot.
create table research_jobs (
    id          bigint       generated by default as identity primary key,
    ticker      text         not null,
    status      text         not null,                        -- PLANNING | RESEARCHING | REVISING_PLAN | SYNTHESIZING | DONE | FAILED
    plan        text         not null default '[]',            -- JSON: [{id,label,dataSource,why,status}] — plain
                                                                 -- text, not jsonb: this is a JPA entity (not the
                                                                 -- JdbcTemplate-with-cast(?  as jsonb) pattern
                                                                 -- logic_review/macro_keyword_review use), and
                                                                 -- Hibernate can't implicitly cast a String into
                                                                 -- jsonb — same reasoning as TradeDecision.snapshot.
    findings    text         not null default '{}',            -- JSON: step id -> short findings summary
    report      text,                                          -- final markdown, null until DONE
    error       text,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now()
);

create index research_jobs_created_at_idx on research_jobs (created_at desc);
