-- Agent 10 (Technical Analysis). Daily OHLC candles per ticker, backing RSI/SMA/drawdown
-- indicators — Argus previously stored no price history at all, only live tick prices.
create table price_candles (
    id           bigint         generated by default as identity primary key,
    ticker       text           not null,
    candle_date  date           not null,
    open         numeric(18,6)  not null,
    high         numeric(18,6)  not null,
    low          numeric(18,6)  not null,
    close        numeric(18,6)  not null,
    volume       bigint,
    ingested_at  timestamptz    not null default now(),
    unique (ticker, candle_date)
);

create index price_candles_ticker_date_idx on price_candles (ticker, candle_date desc);
