-- On-demand bull-vs-bear researcher debate (TradingAgents-style Researcher Team, adapted to a single
-- combined-JSON call — see RecommendationDebateService javadoc). User-triggered per recommendation via
-- "Debate this call"; never part of the automatic 6-hourly pipeline. Every run is kept (not upserted),
-- so re-running as new information lands builds a small history rather than overwriting.
CREATE TABLE recommendation_debates (
    id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id bigint       NOT NULL REFERENCES recommendations(id) ON DELETE CASCADE,
    bull_case         text         NOT NULL,
    bear_case         text         NOT NULL,
    synthesis         text         NOT NULL,
    verdict           text         NOT NULL,   -- BULL | BEAR | SPLIT
    model             text         NOT NULL,   -- which model actually answered (haiku | local fallback)
    created_at        timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_recommendation_debates_rec ON recommendation_debates (recommendation_id);
