-- V5__portfolio_positions.sql — portfolio holdings + staged PDF import batches (Story 3.1, FR-1).
--
-- First tables in the portfolio domain. An upload is parsed into a staged `portfolio_imports`
-- batch (status = pending); existing positions are untouched until the batch is confirmed, so an
-- upload alone never overwrites confirmed data (FR-1 consequence #3). Forward-only.
--
-- Deliberately minimal — later stories EXTEND these tables rather than rewrite:
--   Story 3.2 adds ACB lots (position_lots) + CAD ACB / purchase-time-FX columns + fx_estimated.
--   Story 3.3 adds corporate-actions handling. Story 3.7 adds the manual-edit audit trail.
-- Money is NUMERIC (never float); timestamps are timestamptz (UTC).

CREATE TABLE portfolio_imports (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename      text         NOT NULL,
    status        text         NOT NULL DEFAULT 'pending',  -- pending | confirmed | discarded
    raw_holdings  jsonb        NOT NULL,                     -- staged parsed preview incl. per-field flags
    message       text,                                      -- top-level parse note (e.g. "no holdings found")
    created_at    timestamptz  NOT NULL DEFAULT now(),
    confirmed_at  timestamptz
);

CREATE TABLE positions (
    id                   bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker               text          NOT NULL,
    company_name         text,
    shares               numeric(20, 6),
    cost_basis           numeric(20, 4),                     -- per FR-1b: original trade currency (CAD ACB lands in 3.2)
    cost_basis_currency  text          NOT NULL DEFAULT 'USD',
    acquisition_date     date,
    needs_review         boolean       NOT NULL DEFAULT false, -- a field couldn't be parsed → flagged for manual entry
    source               text          NOT NULL DEFAULT 'pdf_import', -- pdf_import | manual
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX idx_positions_ticker ON positions (ticker);
