-- Agent 11 (Deep Analyst). One row per analysis run. A run can take many minutes (several LLM passes
-- over a full evidence pack), so status/stage are updated as it goes and the UI can show progress.
-- evidence keeps the exact pack the analysts saw, so any verdict can be audited against its inputs.
CREATE TABLE deep_analysis (
    id                   bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker               text         NOT NULL,
    status               text         NOT NULL,          -- QUEUED | RUNNING | DONE | FAILED
    trigger_source       text         NOT NULL,          -- NIGHTLY | MANUAL | BOOT
    stage                text,                           -- human-readable current stage while RUNNING
    verdict              text,                           -- WORTH_BUYING | NOT_WORTH_BUYING | WAIT
    hold_days            integer,                        -- 7 | 30 | 90, only for WORTH_BUYING
    conviction           integer,                        -- 0-100
    headline             text,
    thesis               text,
    bull_case            text,
    bear_case            text,
    risks                text,                           -- newline-separated
    catalysts            text,                           -- newline-separated
    invalidation         text,                           -- what would change the view
    technical_summary    text,
    fundamental_summary  text,
    catalyst_summary     text,
    macro_summary        text,
    skeptic_view         text,
    guard_notes          text,                           -- deterministic downgrades/caps applied to the LLM verdict
    technical_score      numeric(5,3),
    fundamental_score    numeric(5,3),
    consensus_score      numeric(5,3),
    stages               text,                           -- JSON: per-stage timing and model
    evidence             text,
    model                text,
    error                text,
    created_at           timestamptz  NOT NULL DEFAULT now(),
    started_at           timestamptz,
    finished_at          timestamptz,
    expires_at           timestamptz
);

CREATE INDEX idx_deep_analysis_ticker_created ON deep_analysis (ticker, created_at DESC);
CREATE INDEX idx_deep_analysis_status ON deep_analysis (status);
