-- Agent 13 (Trade Learner) and the plumbing every decision-maker shares with it.
--
-- recommendations.features: the JSON array of feature tokens describing the situation a call was made in
--   (direction, sector, regime, signals present, chart/deep verdicts...). Stored at decision time so the
--   learner can later mine outcomes against the conditions that produced them, not a reconstruction.
-- simulated_trades: the protective stop set at entry from Agent 10's chart, how the trade ended (horizon,
--   stop, or Agent 11 flipping its verdict), and the size multiplier the lessons applied.
ALTER TABLE recommendations ADD COLUMN features text;
-- recommendations.lessons: the learned rules that shaped this call (newline-separated), shown on the card.
ALTER TABLE recommendations ADD COLUMN lessons text;

ALTER TABLE simulated_trades
    ADD COLUMN stop_price      numeric(18,6),
    ADD COLUMN exit_reason     text          NOT NULL DEFAULT 'HORIZON',
    ADD COLUMN size_multiplier numeric(6,3)  NOT NULL DEFAULT 1;

-- A lesson the system learned from its own trades. predicates is a comma-separated set of feature tokens
-- that must ALL be present for the rule to apply. Only ACTIVE rules affect behaviour; a rule becomes
-- ACTIVE only after it replicates on newer, held-out trades.
CREATE TABLE learned_rule (
    id                  bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind                text          NOT NULL,   -- PENALTY | BOOST | BLOCK | CAP_HOLD | SIZE
    predicates          text          NOT NULL,
    description         text          NOT NULL,   -- plain English, generated from the numbers
    explanation         text,                     -- the LLM's hypothesis for WHY (informational only)
    effect_value        numeric(8,3)  NOT NULL,   -- points for PENALTY/BOOST, days for CAP_HOLD, multiplier for SIZE
    status              text          NOT NULL,   -- PROPOSED | ACTIVE | RETIRED | REJECTED
    support_trades      integer       NOT NULL DEFAULT 0,
    support_clusters    integer       NOT NULL DEFAULT 0,   -- independent bets (one per ticker-day), not raw trades
    win_rate            numeric(6,4),
    mean_excess         numeric(8,3),             -- average return vs SPY over the fit window, in percent
    holdout_clusters    integer,
    holdout_mean_excess numeric(8,3),
    verdict_note        text,                     -- why it was activated / rejected / retired
    created_at          timestamptz   NOT NULL DEFAULT now(),
    activated_at        timestamptz,
    retired_at          timestamptz,
    last_evaluated_at   timestamptz
);
CREATE INDEX idx_learned_rule_status ON learned_rule (status);

-- The learner's periodic write-up of what is winning and losing and why.
CREATE TABLE learning_report (
    id               bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    trades_analyzed  integer      NOT NULL,
    clusters         integer      NOT NULL,
    baseline_win     numeric(6,4),
    baseline_excess  numeric(8,3),
    losses_summary   text,
    wins_summary     text,
    narrative        text,
    model            text
);
