-- Filings & earnings reader (Agent 14): one row per SEC filing the reader has digested. The digest is the
-- model's structured extraction; the score is computed by code from the extracted fields (never by the model).
CREATE TABLE filing_digest (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker          text          NOT NULL,
    accession       text          NOT NULL UNIQUE,
    form            text          NOT NULL,          -- 8-K | 10-Q | 10-K
    kind            text          NOT NULL,          -- EARNINGS_RELEASE | QUARTERLY_REPORT | ANNUAL_REPORT
    filed_at        date          NOT NULL,
    summary         text,
    guidance        text,                            -- RAISED | MAINTAINED | LOWERED | NONE
    guidance_detail text,                            -- only figures that were verified against the source text
    tone            text,                            -- POSITIVE | NEUTRAL | NEGATIVE
    score           numeric(5,3)  NOT NULL,          -- -1..+1, computed from the fields by fixed rules
    payload         text          NOT NULL,          -- the full verified structured extraction (JSON)
    verified_facts  integer       NOT NULL DEFAULT 0,
    dropped_facts   integer       NOT NULL DEFAULT 0, -- figures the model reported that were NOT in the source, discarded
    source_chars    integer       NOT NULL DEFAULT 0,
    model           text,
    created_at      timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX idx_filing_digest_ticker_filed ON filing_digest (ticker, filed_at DESC);

-- Thesis tracker (Agent 11): a structured level that would prove a verdict wrong, the price at analysis (for the
-- scorecard), and a live status the tracker updates as new information arrives.
ALTER TABLE deep_analysis
    ADD COLUMN invalidation_price  numeric(18,6),
    ADD COLUMN price_at_analysis   numeric(18,6),
    ADD COLUMN thesis_status       text        NOT NULL DEFAULT 'INTACT',   -- INTACT | AT_RISK
    ADD COLUMN thesis_reason       text,
    ADD COLUMN thesis_checked_at   timestamptz;
