-- Agent 15 (Academic Strategies). The published cross-sectional return-predictor literature as a
-- machine-checkable library, plus the wider ranking universe those strategies need.
--
-- The corpus is imported from Chen & Zimmermann's Open Source Asset Pricing documentation
-- (openassetpricing.com, GPL-2), which already carries each signal's exact definition, its original
-- paper, the published t-stat, the portfolio construction rules, AND the authors' own replication
-- grade. It is fetched at runtime rather than vendored, so no GPL content lives in this repo.
--
-- Nothing here is trusted on publication alone: `status` only reaches ACTIVE after a strategy both
-- computes on Argus's own data and survives a chronological hold-out backtest (strategy_backtest).

create table academic_strategy (
    acronym            text          primary key,
    name               text          not null,
    authors            text,
    year               integer,
    journal            text,
    -- PREDICTOR | PLACEBO (published but shown NOT to predict) | DROP
    kind               text          not null,
    -- Accounting | Price | Analyst | Trading | Options | 13F | Event | Other — what data it needs
    data_category      text,
    economic_category  text,
    definition         text,
    published_t_stat   numeric(10,4),
    published_return   numeric(10,4),
    -- +1 = high signal predicts high returns, -1 = high signal predicts low returns
    sign               numeric(4,1),
    ls_quantile        numeric(6,4),
    rebalance_months   numeric(6,2),
    stock_weight       text,
    sample_start_year  integer,
    sample_end_year    integer,
    -- Chen & Zimmermann's own replication verdict: 1_clear | 2_likely | indirect | 4_not | 9_drop
    replication_grade  text,
    gscholar_cites     integer,
    -- whether Argus can actually compute it from the data it has (set by the feasibility classifier)
    computable         boolean       not null default false,
    -- our implemented signal id in SignalLibrary, null until implemented
    implementation     text,
    -- CANDIDATE (implemented, not yet validated) | ACTIVE (passed hold-out) | REJECTED | UNIMPLEMENTED
    status             text          not null default 'UNIMPLEMENTED',
    imported_at        timestamptz   not null default now()
);

create index academic_strategy_kind_idx on academic_strategy (kind, computable);
create index academic_strategy_status_idx on academic_strategy (status);

-- The cross-sectional ranking universe (S&P 500 by default). Deliberately SEPARATE from
-- KnownUniverse: these tickers are ranked against each other so a held name's percentile is
-- meaningful, but they are never traded, never recommended on, and never analysed by Agents 1-14.
create table strategy_universe (
    ticker            text          primary key,
    name              text,
    gics_sector       text,
    gics_sub_industry text,
    source            text          not null,
    active            boolean       not null default true,
    added_at          timestamptz   not null default now()
);

create index strategy_universe_active_idx on strategy_universe (active);

-- One strategy's measured performance on Argus's own data at one horizon. The hold-out columns are
-- the gate: a strategy that works in-sample but not out-of-sample is REJECTED, not deployed.
create table strategy_backtest (
    id                  bigint        generated by default as identity primary key,
    acronym             text          not null references academic_strategy (acronym) on delete cascade,
    horizon_days        integer       not null,
    observations        integer       not null,
    -- long-short decile spread, in percent, benchmark-relative
    mean_excess_pct     numeric(12,4),
    t_stat              numeric(10,4),
    win_rate            numeric(6,4),
    train_mean_excess   numeric(12,4),
    train_t_stat        numeric(10,4),
    holdout_mean_excess numeric(12,4),
    holdout_t_stat      numeric(10,4),
    holdout_observations integer,
    -- PASS | FAIL_INSAMPLE | FAIL_HOLDOUT | INSUFFICIENT_DATA
    verdict             text          not null,
    note                text,
    first_date          date,
    last_date           date,
    run_at              timestamptz   not null default now(),
    unique (acronym, horizon_days)
);

-- The latest cross-sectional reading per ticker per strategy — only the most recent date is kept
-- (history is recomputed from candles when backtesting), so this stays small and serves the UI and
-- Agent 15's hot path without re-deriving percentiles on every request.
create table strategy_score (
    acronym      text          not null references academic_strategy (acronym) on delete cascade,
    ticker       text          not null,
    as_of        date          not null,
    raw_value    numeric(20,8),
    -- 0..1 rank within the universe on that date
    percentile   numeric(8,6)  not null,
    computed_at  timestamptz   not null default now(),
    primary key (acronym, ticker)
);

create index strategy_score_ticker_idx on strategy_score (ticker);
