-- Agent 11's track record, persisted rather than only held in a 10-minute in-memory cache
-- (DeepScorecardService). One row per (verdict, horizon) cell per snapshot run, so the history of how
-- Agent 11's own calls have done against the S&P 500 survives a restart and can be charted over time —
-- not just read as a single "right now" number.
create table deep_scorecard_snapshot (
    id               bigint        generated by default as identity primary key,
    verdict          text          not null,
    horizon_days     integer       not null,
    observations     integer       not null,
    mean_excess_pct  numeric(12,4) not null,
    -- null for WAIT, which makes no directional claim and so has no hit rate.
    hit_rate         numeric(6,4),
    -- how many verdicts existed in total across the whole scorecard at snapshot time, for context.
    total_verdicts   integer       not null,
    computed_at      timestamptz   not null default now()
);

create index deep_scorecard_snapshot_lookup_idx on deep_scorecard_snapshot (verdict, horizon_days, computed_at desc);
