-- V6__position_lots_and_fx.sql — per-lot cost basis + purchase-time FX (Story 3.2, FR-1b).
--
-- Lots become the source of truth for cost; a position's cost basis is the weighted-average
-- across its lots (Canadian non-registered ACB convention, A-16), in both the trade currency and
-- CAD-at-purchase-FX. `positions` keeps cached weighted-average values for fast reads.
-- Forward-only. Story 3.3 will adjust lots for corporate actions; 3.7 adds manual lot CRUD.

CREATE TABLE position_lots (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id     bigint        NOT NULL REFERENCES positions (id) ON DELETE CASCADE,
    shares          numeric(20, 6) NOT NULL,
    total_cost      numeric(20, 4),                 -- lot cost in trade currency (nullable if unparsed)
    trade_currency  text          NOT NULL DEFAULT 'USD',
    trade_date      date,                            -- purchase date (drives the FX lookup)
    fx_to_cad       numeric(18, 8),                  -- USD/CAD at trade_date; CAD lot = 1; null = unknown
    fx_estimated    boolean       NOT NULL DEFAULT false,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    updated_at      timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX idx_position_lots_position ON position_lots (position_id);

-- Cached weighted-average CAD ACB + an "any lot's FX is estimated" flag on the position.
ALTER TABLE positions
    ADD COLUMN cad_acb       numeric(20, 4),
    ADD COLUMN fx_estimated  boolean NOT NULL DEFAULT false;

-- Historical USD/CAD rate cache (Bank of Canada Valet). Keyed by the requested date so a repeat
-- lookup never re-fetches; CAD→CAD short-circuits in code and is never stored here.
CREATE TABLE fx_rates (
    pair        text          NOT NULL,
    rate_date   date          NOT NULL,            -- the date that was requested
    rate        numeric(18, 8) NOT NULL,           -- resolved rate (nearest prior business day)
    source      text          NOT NULL,
    fetched_at  timestamptz   NOT NULL DEFAULT now(),
    PRIMARY KEY (pair, rate_date)
);

-- Backfill: every Story-3.1 position becomes one lot, with no data loss. CAD holdings get FX = 1
-- (exact); USD holdings predate the FX feature so their purchase FX is unknown → flagged estimated
-- until the user confirms a rate/date (Story 3.2 AC #4/#5).
INSERT INTO position_lots
    (position_id, shares, total_cost, trade_currency, trade_date, fx_to_cad, fx_estimated, created_at, updated_at)
SELECT id, shares, cost_basis, cost_basis_currency, acquisition_date,
       CASE WHEN cost_basis_currency = 'CAD' THEN 1 ELSE NULL END,
       CASE WHEN cost_basis_currency = 'CAD' THEN false ELSE true END,
       now(), now()
FROM positions;

UPDATE positions SET
    cad_acb      = CASE WHEN cost_basis_currency = 'CAD' THEN cost_basis ELSE NULL END,
    fx_estimated = CASE WHEN cost_basis_currency = 'CAD' THEN false ELSE true END;
