-- V76__breaking_alert_per_user_read.sql — "Done Reading" on a breaking alert was a single global
-- `read` flag on breaking_alert, so one person dismissing an alert hid it for EVERY signed-in user.
-- Replaced with a per-user read record: the breaking_alert row itself (headline, summary, audit
-- trail) stays shared market-wide content, but each person's own dismissal is personal.

create table breaking_alert_read (
    id        bigint      generated by default as identity primary key,
    alert_id  bigint      not null references breaking_alert(id) on delete cascade,
    user_id   bigint      not null references app_user(id) on delete cascade,
    read_at   timestamptz not null default now(),
    unique (alert_id, user_id)
);
create index idx_breaking_alert_read_user on breaking_alert_read (user_id);

-- Superseded by the per-user table above.
alter table breaking_alert drop column read;
