-- V7__corporate_actions.sql — corporate-actions handling (Story 3.3, FR-1c).
--
-- Records detected/manual corporate actions and their application status. Unambiguous
-- splits/reverse-splits/ticker-changes on a single matched position are auto-applied; everything
-- ambiguous (no/multiple match, merger, stock dividend, missing ratio) stays `pending` for manual
-- confirmation so a position is never silently corrupted. Forward-only.

CREATE TABLE corporate_actions (
    id           bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker       text          NOT NULL,                 -- affected symbol (as known at detection)
    position_id  bigint        REFERENCES positions (id) ON DELETE SET NULL,
    type         text          NOT NULL,                 -- split | reverse_split | stock_dividend | ticker_change | merger
    ratio        numeric(20, 8),                         -- split/exchange ratio (2 = 2:1; 0.1 = 1:10 reverse)
    new_ticker   text,                                   -- for ticker_change / merger
    ex_date      date,
    status       text          NOT NULL DEFAULT 'pending', -- pending | applied | dismissed
    note         text,
    source       text          NOT NULL DEFAULT 'manual',  -- manual | finnhub
    created_at   timestamptz   NOT NULL DEFAULT now(),
    applied_at   timestamptz
);

CREATE INDEX idx_corporate_actions_status ON corporate_actions (status);
