-- V81__announcements.sql — "What's new" notes shown once to each person the next time they open Argus.
-- The note itself is shared; having seen it is personal (same split as breaking_alert / breaking_alert_read),
-- so it shows once per person across all their devices.

create table announcement (
    id           bigint      generated by default as identity primary key,
    title        text        not null,
    body         text        not null,            -- one point per line
    published_at timestamptz not null default now()
);

create table announcement_read (
    announcement_id bigint      not null references announcement(id) on delete cascade,
    user_id         bigint      not null references app_user(id) on delete cascade,
    read_at         timestamptz not null default now(),
    primary key (announcement_id, user_id)
);
create index idx_announcement_read_user on announcement_read (user_id);

insert into announcement (title, body) values (
'What''s new in Argus',
'Always up to date — every page now refreshes on its own and catches up the moment you come back to the app. If the server was offline, missed briefings and reports run as soon as it is back.
Live support & resistance — each ticker''s levels are measured from the live price, and the ticker page shows what price and date its data is from.
Every tab on a ticker now says how fresh it is: the chart''s date, when fundamentals were updated, and how old each headline is.
Tickers tab — search with suggestions, filter by call or chart, and sort by any column. The Deep column now shows Agent 11''s real verdict.
"Needs your attention" cards show when each call started and when it was last re-checked, and calls Argus has stopped tracking no longer linger.
The paper investor now manages its trades all day: a stop on every position, trailing stops that lock in gains, half taken off at the target, and an exit when Argus''s own call reverses. The Agents page shows whether managing beats simply holding.
Trending stocks refresh twice a day again, so the watchlist follows what is actually trending now.'
);
