-- V85__holding_guard.sql — protection for each person's REAL holdings (HoldingGuard). Argus cannot place orders at
-- the user's brokers (no API), so it keeps a recommended protective stop per holding for them to set as a standing
-- stop order at the broker (option A), alerts when something needs action, and — if nobody responds within
-- 15 minutes — makes and records the decision itself and escalates (option B, decide-record-escalate).

-- Opt-in per person: protection pushes and emails on its own, so nobody gets it without choosing it. On for the
-- admin (who asked for it); everyone else turns it on from their Portfolio page.
alter table app_user add column guard_enabled boolean not null default false;
update app_user set guard_enabled = true where is_admin;

create table holding_guard (
    user_id              bigint      not null references app_user(id) on delete cascade,
    ticker               text        not null,
    account              text        not null default '',
    stop_price           numeric(18,6) not null,   -- the recommended stop; only ever tightened
    initial_stop         numeric(18,6) not null,
    start_price          numeric(18,6) not null,   -- price when protection began (breakeven reference)
    high_water           numeric(18,6) not null,
    stop_changed_at      timestamptz not null default now(),
    broker_stop          numeric(18,6),            -- what the person confirmed they set at the broker
    broker_confirmed_at  timestamptz,
    created_at           timestamptz not null default now(),
    primary key (user_id, ticker, account)
);

create table guard_alert (
    id                  bigint      generated by default as identity primary key,
    user_id             bigint      not null references app_user(id) on delete cascade,
    ticker              text        not null,
    account             text        not null default '',
    kind                text        not null,   -- STOP_BROKEN | STOP_RAISED | CALL_REVERSED | THESIS_AT_RISK
    recommendation      text        not null,   -- SELL | TIGHTEN
    detail              text        not null,
    price               numeric(18,6),
    stop_price          numeric(18,6),
    dedupe_key          text        not null,
    status              text        not null default 'OPEN',  -- OPEN | DECIDED
    escalation_level    integer     not null default 0,       -- 0 alerted, 1 reminded, 2 decided by Argus
    created_at          timestamptz not null default now(),
    decided_at          timestamptz,
    decided_by          text,                    -- USER | ARGUS
    decision            text,                    -- SELL | TIGHTEN | HOLD
    price_at_decision   numeric(18,6),
    price_after         numeric(18,6),           -- a week later, to judge the decision
    outcome_pct         numeric(10,4),           -- price change after the decision (negative after a SELL = saved)
    unique (user_id, dedupe_key)
);
create index idx_guard_alert_open on guard_alert (status) where status = 'OPEN';
create index idx_guard_alert_user on guard_alert (user_id, created_at desc);
