-- V87__trade_lesson.sql — S-B3: one structured lesson per closed paper trade.
-- Why Argus entered (the call, its conviction/odds, the signals that drove it), how it ended, the lesson
-- (the Analyst's post-mortem on a loss; which signals were right on a win), and what changed afterwards
-- (a logic-review weight change, an Agent 13 rule activated/retired, or an explicit NO_CHANGE). Keyed on the
-- paper trade, not the recommendation: one call can open several legs.
create table trade_lesson (
    id                bigint       generated by default as identity primary key,
    trade_id          bigint       not null unique references simulated_trades(id) on delete cascade,
    recommendation_id bigint,
    ticker            text         not null,
    direction         text         not null,
    won               boolean      not null,
    exit_reason       text,
    closed_at         timestamptz  not null,
    why_entered       text         not null,
    outcome           text         not null,
    lesson            text         not null,
    relied_on         text,                                   -- comma-separated agent ids that drove the call
    change_kind       text         not null default 'PENDING', -- PENDING | WEIGHTS_ADJUSTED | RULE_ACTIVATED | RULE_RETIRED | NO_CHANGE
    change_summary    text,
    change_checked_at timestamptz,
    created_at        timestamptz  not null default now()
);

create index trade_lesson_closed_at_idx on trade_lesson (closed_at desc);
create index trade_lesson_ticker_idx on trade_lesson (ticker);
create index trade_lesson_pending_idx on trade_lesson (change_kind) where change_kind = 'PENDING';
