-- V8__portfolio_value_history.sql — daily portfolio value series for the chart (Story 3.6, FR-4).
--
-- One CAD-value point per day (captured_on UNIQUE → idempotent upsert). Populated by a scheduled
-- daily capture of the live portfolio total; the chart queries a date window. Forward-only.

CREATE TABLE portfolio_value_history (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captured_on     date          NOT NULL UNIQUE,
    total_value_cad numeric(20, 2) NOT NULL,
    created_at      timestamptz   NOT NULL DEFAULT now()
);
