-- V9__position_audit.sql — manual position-edit audit trail (Story 3.7, FR-5).
--
-- Append-only log of manual add/edit/remove actions, each timestamped. Visibility only (not a
-- transactional rollback log). Forward-only.

CREATE TABLE position_audit (
    id          bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker      text          NOT NULL,
    action      text          NOT NULL,   -- created | updated | removed
    detail      text,
    created_at  timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX idx_position_audit_created ON position_audit (created_at DESC);
